In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
df=pd.read_csv("IRIS.csv")
df.head()

In [ ]:
df.species.unique()

In [ ]:
df.shape


In [ ]:
df.drop("species",axis=1,inplace=True)

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
reduced_data=pca.fit_transform(df)
print("Reduced Data Shape:", reduced_data.shape)
print(reduced_data)
pca_data=pd.DataFrame(data=reduced_data,columns=['pca1','pca2'])
pca_data

In [ ]:
df1=pd.DataFrame(reduced_data,columns=['PC1','Pc2'])
df1

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Iris dataset
df = pd.read_csv('iris.csv')  # Update the path to your dataset

print(df.head(10))
# Separate features and target
X = df.drop('species', axis=1)  # Only features
y = df['species']               # Target variable

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA with 2 components
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Create a DataFrame with PCA results and target
pca_df = pd.DataFrame(data=X_pca, columns=['Principal Component 1', 'Principal Component 2'])
pca_df = pd.concat([pca_df, y.reset_index(drop=True)], axis=1)


print(pca_df.head(10))

# Plot the PCA results
plt.figure(figsize=(10, 6))
sns.scatterplot(data=pca_df, x='Principal Component 1', y='Principal Component 2', hue='species', palette='Set1')
plt.title('PCA of IRIS Dataset')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(loc='best')  
plt.show()

# Print explained variance ratio
print("Explained variance by each component:", pca.explained_variance_ratio_)
print("Total explained variance:", sum(pca.explained_variance_ratio_))



In [ ]:
df

# PCA 


In [ ]:
df=pd.read_csv("IRIS.csv")


In [ ]:
# from sklearn.decomposition import PCA
# from sklearn.preprocessing import StandardScaler
# x=df.drop('species',axis=1)
# y=df['species']

# # Step 2: Standardize the features
# x=StandardScaler().fit_transform(x)

# # apply pca
# pca=PCA(n_components=2)
# x_pca=pca.fit_transform(x)

# # Step 4: Create a DataFrame for PCA results
# pca_df=pd.DataFrame(x_pca,columns=['pc1','pc2'])
# pca_df['species']=y

# from sklearn.preprocessing import LabelEncoder
# encoder=LabelEncoder()
# labeled=encoder.fit_transform(y)



# # Step 5: Plot the results
# plt.figure(figsize=(8,5))
# plt.scatter(pca_df['pc1'],pca_df['pc2'],c=labeled,cmap="viridis")
# plt.title('PCA on Iris Dataset')
# plt.xlabel('Principal Component 1')
# plt.ylabel('Principal Component 2')
# plt.colorbar(label='Species')
# plt.show()
# x_pca

# or

In [ ]:
df.columns

In [ ]:
# from sklearn.decomposition import PCA
# x=df.drop("species",axis=1)
# y=df['species']

# pca=PCA(n_components=2)
# x_pca=pca.fit_transform(x)

# pca_df=pd.DataFrame(x_pca,columns=['pc1','pc2'])
# pca_df['species']=y

# from sklearn.preprocessing import LabelEncoder
# encoder=LabelEncoder()
# labeled=encoder.fit_transform(y)

# plt.figure(figsize=(8,5))
# plt.scatter(pca_df['pc1'],pca_df['pc2'],c=labeled,cmap="viridis")



In [ ]:
df

In [ ]:
from sklearn.decomposition import PCA
x=df.drop("species",axis=1)
y=df['species']

from sklearn.preprocessing import StandardScaler
x=StandardScaler().fit_transform(x)

pca=PCA(n_components=2)
x_pca=pca.fit_transform(x)

df1=pd.DataFrame(x_pca,columns=['PC1','PC2'])
df1['species']=y

from sklearn.preprocessing import LabelEncoder

enco=LabelEncoder()
labeled_Y=enco.fit_transform(y)

plt.figure(figsize=(6,5))
plt.scatter(df1['PC1'],df1['PC2'],c=labeled_Y,cmap='viridis')

# svd

In [ ]:
from sklearn.decomposition import TruncatedSVD
x=df.drop("species",axis=1)
y=df["species"]

from sklearn.preprocessing import StandardScaler
x=StandardScaler().fit_transform(x)

u,sigma,vt=np.linalg.svd(x)


# svd=TruncatedSVD(n_components=2)
# x_svd=svd.fit_transform(x)

# svd_df=pd.DataFrame(x_svd,columns=['SVD Component 1', 'SVD Component 2'])
# svd_df['species']=y
# from  sklearn.preprocessing import LabelEncoder
# encoder=LabelEncoder()
# labeled=encoder.fit_transform(y)

# plt.scatter(svd_df['SVD Component 1'],svd_df['SVD Component 2'],c=labeled,cmap='viridis')
# svd_df

In [ ]:
u,sigma,vt

In [ ]:
df
x,y
u,sigma,vt=np.linalg.svd(x)


In [ ]:
# Step 1: Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Step 2: Load the Iris dataset and drop the species column (keep only numeric columns)
df = pd.read_csv('iris.csv')  # Replace with your path
X = df.drop(columns='species')

# Step 3: Standardize the data (mean=0, variance=1)
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

# Step 4: Apply SVD using numpy
U, Sigma, Vt = np.linalg.svd(X_standardized)

# Step 5: Take the first two components to reduce dimensions to 2D
X_svd_2d = X_standardized @ Vt.T[:, :2]

# Step 6: Plot the 2D representation
plt.figure(figsize=(8, 5))
plt.scatter(X_svd_2d[:, 0], X_svd_2d[:, 1], c=pd.factorize(df['species'])[0], cmap='viridis', edgecolor='k', s=50)
plt.title("Iris Dataset in 2D (Using SVD)")
plt.xlabel("SVD Component 1")
plt.ylabel("SVD Component 2")
plt.colorbar(label='Species')
plt.grid(True)
plt.show()

U,Sigma,Vt

# linear regression 

In [ ]:
# # Import libraries
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# from sklearn.preprocessing import StandardScaler, LabelEncoder
# from sklearn.metrics import mean_squared_error, r2_score

# # Load the dataset
# df = pd.read_csv('iris.csv')  # Update with your path

# # Encode the species column
# label_encoder = LabelEncoder()
# df['species_encoded'] = label_encoder.fit_transform(df['species'])

# # Prepare features and target variable
# X = df.drop(['species', 'species_encoded', 'petal_length'], axis=1)
# y = df['petal_length']

# # Standardize the features
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)

# # Split the data
# X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# # Train the model
# model = LinearRegression()
# model.fit(X_train, y_train)

# # Make predictions
# y_pred = model.predict(X_test)

# # Evaluate the model
# mse = mean_squared_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

# print(f'Mean Squared Error: {mse:.2f}')
# print(f'R-squared: {r2:.2f}')

# # Check predictions
# predictions_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
# print("\nComparison of Actual vs Predicted values:")
# print(predictions_df.reset_index(drop=True))


In [ ]:
df

# prediction 

In [ ]:
df

In [ ]:
# dummies=pd.get_dummies(df.species).astype(int)
# dummies.head()


# df1=pd.concat([df,dummies],axis='columns')
# df1.drop("species",axis=1,inplace=True)
# df1

# x=df1.drop('petal_length',axis=1)
# y=df1['petal_length']


# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)


# from sklearn.linear_model import LinearRegression
# li=LinearRegression()
# li.fit(x_train,y_train)
# li.score(x_test,y_test)


# def predict_petal_lenght(sepal_length,sepal_width,petal_width,species):
#     sep_index=np.where(x.columns==species)[0][0]

#     a=np.zeros(len(x.columns))
#     a[0]=sepal_length
#     a[1]=sepal_width
#     a[2]=petal_width

#     if sep_index>=0:
#         a[sep_index]=1
#     return li.predict([a])[0]


In [ ]:
# predict_petal_lenght(5.1,3.5,0.2,'Iris-setosa')

In [ ]:
df.head()

In [ ]:
dummies=pd.get_dummies(df['species']).astype(int)
dummies
new=pd.concat([df,dummies],axis=1)
new.drop("species",axis=1,inplace=True)
new
# predict the sepal length
x=new.drop('sepal_length',axis=1)
y=new['sepal_length']

from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

print(x_train.shape)
print(y_train.shape)


In [ ]:
from sklearn.linear_model import LinearRegression
li=LinearRegression()
li.fit(x_train,y_train)
li.score(x_test,y_test)

# other way

In [ ]:
# Step 1: Import the necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt

# Step 2: Load the Iris dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
iris = pd.read_csv(url, header=None, names=column_names)

# Step 3: Prepare the data
X = iris[['sepal_length', 'sepal_width']]  # Features
y = iris['petal_length']                    # Target variable

# Step 4: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Create and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 6: Make predictions
y_pred = model.predict(X_test)

# Step 7: Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')
print(f'R-squared: {r2}')

# Step 8: Visualize the results
plt.scatter(y_test, y_pred, alpha=0.7)
plt.xlabel('Actual Petal Length')
plt.ylabel('Predicted Petal Length')
plt.legend(iris)
plt.title('Actual vs Predicted Petal Length')
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', linestyle='--')  # Line for perfect predictions
plt.show()


In [ ]:
import numpy as np

# Example data for covariance
data = np.array([[2.5, 3.1, 2.8],
                 [3.6, 3.9, 4.1],
                 [4.0, 3.7, 3.3]])

# Covariance matrix
cov_matrix = np.cov(data, rowvar=False)
print("Covariance Matrix:\n", cov_matrix)

# Example matrix for transpose and inverse
matrix = np.array([[4, 7],
                   [2, 6]])

# Transpose of the matrix    
transpose_matrix = matrix.T
print("Transpose Matrix:\n", transpose_matrix)

# Inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
print("Inverse Matrix:\n", inverse_matrix)


In [8]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
data = np.array([[1, 2], [3, 4], [5, 6]])

# Matrix operations
print("Matrix Addition:\n", A + B)
print("Matrix Subtraction:\n", A - B)
print("Element-wise Multiplication:\n", A * B)
print("Dot Product:\n", np.dot(A, B))
print("Transpose of A:\n", A.T)
print("Determinant of A:", np.linalg.det(A))
print("Inverse of A:\n", np.linalg.inv(A))
print("Rank of A:", np.linalg.matrix_rank(A))
print("Trace of A:", np.trace(A))
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)
print("Covariance Matrix of data:\n", np.cov(data, rowvar=False))
U, S, V = np.linalg.svd(A)
print("SVD of A:\n", U, S, V)
print("Solution for Ax=B:\n", np.linalg.solve(A, np.array([9, 8])))
print("Matrix Power (A^2):\n", np.linalg.matrix_power(A, 2))
print("Norm of A:", np.linalg.norm(A))

np.cross(A,B)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Rank of A: 2
Trace of A: 5
Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Covariance Matrix of data:
 [[4. 4.]
 [4. 4.]]
SVD of A:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] [5.4649857  0.36596619] [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Solution for Ax=B:
 [-10.    9.5]
Matrix Power (A^2):
 [[ 7 10]
 [15 22]]
Norm of A: 5.477225575051661


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20156\754356776.py:28: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(A,B)


array([-4, -4])

In [5]:
nums=[2,1,3,4,6,8]
arr1=[nums[0]]
arr2=[nums[1]]
for i in range(2,len(nums)):
    if arr1[-1]>arr2[-1]:
        arr1.append(nums[i])
    else:
        arr2.append(nums[i])
arr1.extend(arr2)
arr1


[2, 3, 4, 6, 8, 1]